name: Node CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: npm install
      run: |
        npm install
    - name: release
      run: |
        npm run release
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
